<<<<<<< Updated upstream
# Generated by Django 3.1.6 on 2021-02-18 23:46
=======
# Generated by Django 3.1.6 on 2021-02-19 00:05
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('location', models.CharField(max_length=30, verbose_name='Местоположение')),
                ('x_coord', models.FloatField(verbose_name='Координата X')),
                ('y_coord', models.FloatField(verbose_name='Координата Y')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Метка(*)',
                'verbose_name_plural': 'Метки(*)',
<<<<<<< Updated upstream
            },
        ),
        migrations.CreateModel(
            name='UImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=map.models.get_image_filename, verbose_name='Изображение')),
                ('tag_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.unverifiedtag')),
            ],
        ),
        migrations.CreateModel(
=======
            },
        ),
        migrations.CreateModel(
            name='UImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=map.models.get_image_filename, verbose_name='Изображение')),
                ('tag_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.unverifiedtag')),
            ],
            options={
                'verbose_name': 'Изображения(*)',
                'verbose_name_plural': 'Изображения(*)',
            },
        ),
        migrations.CreateModel(
>>>>>>> Stashed changes
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('location', models.CharField(max_length=30, verbose_name='Местоположение')),
                ('x_coord', models.FloatField(verbose_name='Координата X')),
                ('y_coord', models.FloatField(verbose_name='Координата Y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=map.models.get_image_filename, verbose_name='Изображение')),
                ('tag_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.tag')),
            ],
<<<<<<< Updated upstream
=======
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения(*)',
            },
>>>>>>> Stashed changes
        ),
    ]
