# Generated by Django 3.1.6 on 2021-02-25 04:40

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedtag',
            name='image',
            field=models.FileField(blank=True, default='no pic', upload_to=map.models.UnverifiedTag.images_directory_path, verbose_name='Изображение'),
        ),
    ]
