# Generated by Django 3.1.6 on 2021-02-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifiedtag',
            old_name='email',
            new_name='user',
        ),
    ]
