# Generated by Django 3.1.6 on 2021-02-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
    ]
