# Generated by Django 3.1.6 on 2021-02-16 03:33

from django.db import migrations, models
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210216_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unverifiedtag',
            options={'verbose_name': 'Метка(*)', 'verbose_name_plural': 'Метки(*)'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='no pic', upload_to=map.models.Tag.images_directory_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='unverifiedtag',
            name='image',
            field=models.FileField(default='no pic', upload_to=map.models.UnverifiedTag.images_directory_path, verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='VerifiedTag',
        ),
    ]
