# Generated by Django 3.1.6 on 2021-02-19 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_auto_20210219_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='x_coord',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='y_coord',
            field=models.FloatField(blank=True, null=True, verbose_name='Координата Y'),
        ),
    ]
