# Generated by Django 3.1.6 on 2021-02-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210211_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedtag',
            name='x_coord',
            field=models.FloatField(verbose_name='Координата X'),
        ),
        migrations.AlterField(
            model_name='verifiedtag',
            name='y_coord',
            field=models.FloatField(verbose_name='Координата Y'),
        ),
    ]
